replicaCount: 1
image:
  repository: docker.io/abdreyes/microservice
  tag: "01ab9ee"
  pullPolicy: IfNotPresent
appVersion: "01ab9ee"
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
env:
  APP_NAME: "microservice"
  ENVIRONMENT: "k8s-local"
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"
probes:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
